config/routes.rb
Rails.application.routes.draw do
  # * devise_for ini berasal dari generate devise
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # ! Cara bacanya method-url-controllermethod-alias(opsional)
  # get "/blog_posts/new", to: "blog_posts#new", as: :new_blog_post
  # post "/blog_posts", to: "blog_posts#create", as: :blog_posts
  # get "/blog_posts/:id", to: "blog_posts#show", as: :blog_post
  # patch "/blog_posts/:id", to: "blog_posts#update"
  # delete "/blog_posts/:id", to: "blog_posts#destroy"
  # get "/blog_posts/:id/edit", to: "blog_posts#edit", as: :edit_blog_post
  # * as: :alias ini adalah alias untuk mempersingkat "to: "blablabla" "
  # ! Route dengan parameter :id harus di paling bawah
  # * MAGIC, cukup gunakan code di bawah untuk meringkas banyak route di atas
  resources :blog_posts do
    # TODO: Intinya Pahami kode di bawah
    resource :cover_image, only: [:destroy], module: :blog_posts
  end

  # Defines the root path route ("/")
  root 'blog_posts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog_post.rb
class BlogPost < ApplicationRecord
  has_one_attached :cover_image
  has_rich_text :content

  validates :title, presence: true
  validates :content, presence: true

  # TODO: Pelajari lagi code lambda di bawah ini
  # scope :sorted, -> { order(published_at: :desc, updated_at: :desc) }
  # ! Intinya coding di atas tidak berjalan sebagaimana mestinya
  # ! Karena harusnya urutannya scheduled-publish-draft tapi coding di atas malah tidak berjalan
  # * Maka dari itu ada 2 opsi untuk melakukan query
  # * Pertama - Pakai raw Query dari PostgreSQL
  # * scope :sorted, -> { order(Arel.sql('published_at DESC NULLS LAST')).order(updated_at: :desc) }
  # * Kedua - Pakai Query Ruby
  scope :sorted, -> { order(arel_table[:published_at].desc.nulls_first).order(updated_at: :desc) }
  scope :draft, -> { where(published_at: nil) }
  scope :published, -> { where('published_at <= ?', Time.current) }
  scope :scheduled, -> { where('published_at > ?', Time.current) }

  def draft?
    published_at.nil?
  end

  def published?
    published_at? && published_at <= Time.current
  end

  def scheduled?
    published_at? && published_at > Time.current
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  # ! devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
  # ! Alasan kenapa :registerable ku hapus supaya tidak ada user luar yang membuat akun baru di blog milikku
  # * Alangkah baiknya untuk memasukkan data user melalui console saja
  devise :database_authenticatable, :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend
end

app/controllers/blog_posts/cover_images_controller.rb
class BlogPosts::CoverImagesController < ApplicationController
  include ActionView::RecordIdentifier
  # TODO: Pelajari semua implementasi kode di FILE INI!!!
  before_action :authenticate_user!
  before_action :set_blog_post

  def destroy
    @blog_post.cover_image.purge_later

    respond_to do |format|
      format.html { redirect_to edit_blog_post_path(@blog_post) }
      format.turbo_stream { render turbo_stream: turbo_stream.remove(dom_id(@blog_post, :cover_image))}
    end
  end

  private
  def set_blog_post
    @blog_post = BlogPost.find(params[:blog_post_id])
  end
end

app/controllers/blog_posts_controller.rb
# frozen_string_literal: true
class BlogPostsController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]
  before_action :set_blog_post, only: %i[show edit update destroy]
  # bisa juga pakai except(kecuali): [:index, :new, :create]

  def index
    @blog_posts = user_signed_in? ? BlogPost.sorted : BlogPost.published
    @pagy, @blog_posts = pagy(@blog_posts)
  rescue Pagy::OverflowError
    # * Opsi pertama, mengembalikan page=over ke halaman 1, ramah SEO
    redirect_to root_path(page: 1)
    # * Opsi kedua, mengembalikan page=over ke halaman 1 TAPI tetep menggunakan url ngawur tadi. misal 100 menjadi 101 tapi datanya data halam ke 1, kelemahannya tidak ramah SEO
    # params[:page] = 1
    # retry
  end

  def show
    # @blog_post = BlogPost.find(params[:id])
    # rescue ActiveRecord::RecordNotFound
    #   redirect_to root_path
  end

  def new
    @blog_post = BlogPost.new
  end

  def create
    # @blog_post = BlogPost.new(params[blog_post]) #! Ini tidak aman, makanya dibuat private di bawah
    @blog_post = BlogPost.new(blog_post_params)
    if @blog_post.save
      redirect_to @blog_post
    else
      render :new, status: :unprocessable_entity
      # status di atas adalah fitur Rails, sehingg server tidak mengirim header 'ok'
    end
  end

  def edit
    # @blog_post = BlogPost.find(params[:id])
  end

  def update
    # @blog_post = BlogPost.find(params[:id])
    if @blog_post.update(blog_post_params)
      redirect_to @blog_post
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    # @blog_post = BlogPost.find(params[:id])
    @blog_post.destroy
    redirect_to root_path
  end

  private

  def blog_post_params
    # * Ada alasan Khusus kenapa ada :content dan :cover_image
    # TODO: Pelajari lagi saja
    params.require(:blog_post).permit(:title, :content, :cover_image, :published_at)
  end

  def set_blog_post
    # * Awalnya Gini
    # if user_signed_in?
    #   @blog_post = BlogPost.find(params[:id])
    # else
    #   @blog_post = BlogPost.published.find(params[:id])
    # end
    # * Jadi gini
    @blog_post = user_signed_in? ? BlogPost.find(params[:id]) : BlogPost.published.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_to root_path
  end

  # def authenticate_user!
  #   redirect_to new_user_session_path, alert: "You must sign in or sign up to continue." unless user_signed_in!
  # end
  # ! Tidak perlu pakai coding ini, karena "authenticate_user" sudah dibuatkan Rails
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/blog_posts/_form.html.erb
<%= form_with model: @blog_post do |form| %>
  <% if form.object.errors.any? %>
    <div>
      <% form.object.errors.full_messages.each do |message| %>
        <div> <%= message %> </div>
      <% end %>
    </div>
  <%end%>

  <div>
    <%= form.label :title%>
    <%= form.text_field :title%>
  </div>

   <div>
     <%= form.label :cover_image %>
     <%# TODO: Pelajari lagi implementasi kode Turbo di bawah %>
     <%  if blog_post.cover_image.present? %>
       <div id="<%= dom_id(blog_post, :cover_image) %>">
         <%= image_tag blog_post.cover_image, class: "w-1/3"%>
         <%= link_to "Remove Cover Image", blog_post_cover_image_path(blog_post), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
       </div>
     <% end %>
     <%= form.file_field :cover_image %>
   </div>

  <div>
    <%= form.label :content%>
    <%= form.rich_text_area :content%>
  </div>

  <div>
    <%= form.label :published_at %>
    <%= form.datetime_select :published_at, include_blank: true %>
  </div>

  <%= form.button%>
<%end%>

app/views/blog_posts/edit.html.erb
<h1>Edit Blog Post</h1>
<%= render partial: "form", locals: {blog_post: @blog_post} %>
<%= button_to "Delete", @blog_post, method: :delete, data: {turbo_confirm: "Are you sure?"} %>

app/views/blog_posts/index.html.erb
<h1>Blog Posts</h1>
<% @blog_posts.each do |blog_post|  %>
  <div>
    <%= image_tag blog_post.cover_image if blog_post.cover_image.present? %>
    <%#* Awalnya gini, (kurung-equal) karena kalau sintax biasa tidak bisa dicomment %>
    <%#* <h2> (kurung-equal) link_to blog_post.title, "/blog_posts/#{blog_post.id}" </h2>%>
    <%#* Setelah membuat alias di controller(as: :bla bla) %>
    <%#* <h2> (kurung-equal) link_to blog_post.title, blog_post_path(blog_post.id) </h2>%>
    <%#* Magic 1 => Tidak perlu pakai id %>
    <%#* <h2> (kurung-equal) link_to blog_post.title, blog_post_path(blog_post) </h2>%>
    <%#* Magic 2 => cukup pakai objectnya saja, Rails pinter %>
    <h2> <%= link_to blog_post.title, blog_post %> </h2>
    <% if blog_post.draft? %>
      <div class="p-2 rounded bg-gray-100 text-gray-900">Draft</div>
    <% elsif blog_post.scheduled? %>
      <div class="p-2 rounded bg-blue-100 text-blue-900">Schedule</div>
    <% end %>
    <p> <%= blog_post.content %> </p>
  </div>
<% end %>

<% if @pagy.count > @pagy.items %>
<div class="mt-16">
  <%== pagy_nav(@pagy) %>
</div>
<% end %>

app/views/blog_posts/new.html.erb
<h1>New Blog Post</h1>
<%# Pake fitur Partial, jadi kayak pake component di react %>
<%= render partial: "form", locals: {blog_post: @blog_post} %>

app/views/blog_posts/show.html.erb
<%= link_to "Home", root_path %>

<%= image_tag @blog_post.cover_image if @blog_post.cover_image.present? %>
<h1> <%= @blog_post.title %> </h1>
<p> <%= @blog_post.content %> </p>
<%= link_to "Edit", edit_blog_post_path(@blog_post) if user_signed_in? %>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>BlogGorails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "actiontext", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body class="prose mx-auto" >
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <div>
      <% if user_signed_in? %>
        <%= link_to "Create New Blog", new_blog_post_path %>
        <%#= link_to "Profile", edit_user_registration_path %>
        <%= button_to "Log Out", destroy_user_session_path, method: :delete %>
        <%# else %>
        <%#= link_to "Login", new_user_session_path %>
        <%#= link_to "Sign Up", new_user_registration_path %>
        <%#! Cuma disisain Log Out ya untuk log out, untuk edit bisa melalui console  %>
        <%#! Untuk login bisa melalui url %>
      <% end %>
    </div>
    <%= yield %>
  </body>
</html>